# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=100)),
                ('member_pw', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('member_age', models.CharField(max_length=20)),
                ('member_gender', models.CharField(max_length=20)),
            ],
        ),
    ]
